[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "deepgram-sdk>=5.3.2",
    "fastapi>=0.129.0",
    "httpx>=0.28.1",
    "python-multipart>=0.0.22",
    "uvicorn>=0.40.0",
]
